set -g default-terminal "tmux-256color"

unbind C-b         

set-option -g prefix C-s
set -g mouse on
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-style bg=black,fg=blue
set -g window-status-current-style bg=blue,fg=black,bold
set -g pane-border-style fg=grey
set -g pane-active-border-style fg=blue
set -g message-style bg=blue,fg=black

set -g status-right "%Y-%m-%d %H:%M"

set -g history-limit 100000

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'leohenon/tmux-tab'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'

# LAST FILE LINE
run '~/.tmux/plugins/tpm/tpm'
